=== aSalvaRipoll/App/Addin/USysRibbons.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:od="urn:schemas-microsoft-com:officedata">
<xsd:element name="dataroot">
<xsd:complexType>
<xsd:sequence>
<xsd:element ref="USysRibbons" minOccurs="0" maxOccurs="unbounded"/>
</xsd:sequence>
<xsd:attribute name="generated" type="xsd:dateTime"/>
</xsd:complexType>
</xsd:element>
<xsd:element name="USysRibbons">
<xsd:annotation>
<xsd:appinfo>
<od:tableProperty name="GUID" type="9" value="zWf99w4YgkOoJxz0U5dEwA==
"/>
<od:tableProperty name="Orientation" type="2" value="0"/>
<od:tableProperty name="OrderByOn" type="1" value="0"/>
<od:tableProperty name="NameMap" type="11" value="CswOVQAAAADNZ/33DhiCQ6gnHPRTl0TAAAAAAKQ2cZq7duZAAAAAAAAAAABVAFMA
eQBzAFIAaQBiAGIAbwBuAHMAAAAAAAAAHWVL6wz2u0KNCtdTMTyKnQcAAADNZ/33
DhiCQ6gnHPRTl0TASQBEAAAAAAAAABa7dnqiH+xIqKhm//Z3rmEHAAAAzWf99w4Y
gkOoJxz0U5dEwFIAaQBiAGIAbwBuAE4AYQBtAGUAAAAAAAAACWWscOkMnEOkKkRl
H9yIOgcAAADNZ/33DhiCQ6gnHPRTl0TAUgBpAGIAYgBvAG4AWABNAEwAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAwAAAAFAAAAAAAAAAAAAAAAAAAAAAA=
"/>
<od:tableProperty name="DefaultView" type="2" value="2"/>
<od:tableProperty name="DisplayViewsOnSharePointSite" type="2" value="1"/>
<od:tableProperty name="TotalsRow" type="1" value="0"/>
<od:tableProperty name="FilterOnLoad" type="1" value="0"/>
<od:tableProperty name="OrderByOnLoad" type="1" value="1"/>
<od:tableProperty name="HideNewField" type="1" value="0"/>
<od:tableProperty name="BackTint" type="6" value="100"/>
<od:tableProperty name="BackShade" type="6" value="100"/>
<od:tableProperty name="ThemeFontIndex" type="4" value="1"/>
<od:tableProperty name="AlternateBackThemeColorIndex" type="4" value="1"/>
<od:tableProperty name="AlternateBackTint" type="6" value="100"/>
<od:tableProperty name="AlternateBackShade" type="6" value="95"/>
<od:tableProperty name="ReadOnlyWhenDisconnected" type="1" value="0"/>
<od:tableProperty name="DatasheetGridlinesThemeColorIndex" type="4" value="3"/>
<od:tableProperty name="DatasheetForeThemeColorIndex" type="4" value="0"/>
<od:tableProperty name="PublishToWeb" type="2" value="1"/>
<od:tableProperty name="RowHeight" type="3" value="6195"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:complexType>
<xsd:sequence>
<xsd:element name="ID" minOccurs="1" od:jetType="autonumber" od:sqlSType="int" od:autoUnique="yes" od:nonNullable="yes" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="HWVL6wz2u0KNCtdTMTyKnQ==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="1"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="RibbonName" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="Frt2eqIf7EioqGb/9neuYQ==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="1800"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="RibbonXML" minOccurs="0" od:jetType="memo" od:sqlSType="ntext">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="CWWscOkMnEOkKkRlH9yIOg==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="15750"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="TextFormat" type="2" value="0"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AppendOnly" type="1" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="536870910"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
</xsd:sequence>
</xsd:complexType>
</xsd:element>
</xsd:schema>

=== aSalvaRipoll/App/Addin/USysRibbons.xml
<?xml version="1.0" encoding="UTF-8"?>
<dataroot xmlns:od="urn:schemas-microsoft-com:officedata" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="USysRibbons.xsd" generated="2025-12-15T09:19:26">
<USysRibbons>
<ID>1</ID>
<RibbonName>Inspector</RibbonName>
<RibbonXML>&lt;customUI xmlns=&quot;http://schemas.microsoft.com/office/2009/07/customui&quot;&gt;
  &lt;ribbon&gt;
    &lt;tabs&gt;
      &lt;tab id=&quot;tabInspector&quot; label=&quot;Inspector VBA&quot;&gt;
        &lt;group id=&quot;grpInspector&quot; label=&quot;Herramientas&quot;&gt;
          &lt;button id=&quot;btnEjecutarInspector&quot;
                  label=&quot;Ejecutar Inspector&quot;
                  imageMso=&quot;TraceError&quot;
                  size=&quot;large&quot;
                  onAction=&quot;OnEjecutarInspector&quot;/&gt;
          &lt;button id=&quot;btnRepararProyecto&quot;
                  label=&quot;Reparar Proyecto&quot;
                  imageMso=&quot;DatabaseEncodeDecode&quot;
                  size=&quot;large&quot;
                  onAction=&quot;OnRepararProyecto&quot;/&gt;
        &lt;/group&gt;
      &lt;/tab&gt;
    &lt;/tabs&gt;
  &lt;/ribbon&gt;
&lt;/customUI&gt;</RibbonXML>
</USysRibbons>
<USysRibbons>
<ID>2</ID>
<RibbonName>InspectorVBAOld</RibbonName>
<RibbonXML>&lt;customUI xmlns=&quot;http://schemas.microsoft.com/office/2009/07/customui&quot;&gt;
  &lt;ribbon&gt;
    &lt;tabs&gt;
      &lt;tab id=&quot;tabInspector&quot; label=&quot;Inspector VBA&quot;&gt;
        &lt;group id=&quot;grpInspector&quot; label=&quot;Herramientas&quot;&gt;
          &lt;button id=&quot;btnEjecutarInspector&quot;
                  label=&quot;Ejecutar Inspector&quot;
                   imageMso=&quot;TraceError&quot;
                  size=&quot;large&quot;
                  onAction=&quot;OnEjecutarInspector&quot;/&gt;
          &lt;button id=&quot;btnRepararProyecto&quot;
                  label=&quot;Reparar Proyecto&quot;
                  imageMso=&quot;DatabaseEncodeDecode&quot;
                  size=&quot;large&quot;
                  onAction=&quot;OnRepararProyecto&quot;/&gt;
        &lt;/group&gt;
      &lt;/tab&gt;
    &lt;/tabs&gt;
  &lt;/ribbon&gt;
&lt;/customUI&gt;</RibbonXML>
</USysRibbons>
<USysRibbons>
<ID>3</ID>
<RibbonName>contextualTabSet1</RibbonName>
<RibbonXML>&lt;customUI xmlns=&quot;http://schemas.microsoft.com/office/2009/07/customui&quot;&gt;

  &lt;ribbon&gt;
    &lt;contextualTabs&gt;

      &lt;!-- ===================================================== --&gt;
      &lt;!-- CINTA PARA FORMULARIO DE RESULTADOS --&gt;
      &lt;!-- ===================================================== --&gt;
      &lt;tabSet idMso=&quot;TabSetForm&quot;&gt;
        &lt;tab id=&quot;tabInspectorResultados&quot; label=&quot;Inspector – Resultados&quot;&gt;
          &lt;group id=&quot;grpAcciones&quot; label=&quot;Acciones&quot;&gt;
            &lt;button id=&quot;btnAnalizar&quot; 
                    label=&quot;Analizar&quot; 
                    imageMso=&quot;Zoom&quot; 
                    onAction=&quot;Ribbon_Analizar&quot;
                    screentip=&quot;Analizar proyecto&quot;
                    supertip=&quot;Ejecuta el análisis completo del proyecto VBA para detectar problemas y generar resultados.&quot; /&gt;
            &lt;button id=&quot;btnReparar&quot; 
                    label=&quot;Reparar&quot; 
                    imageMso=&quot;Repair&quot; 
                    onAction=&quot;Ribbon_Reparar&quot;
                    screentip=&quot;Reparar proyecto&quot;
                    supertip=&quot;Aplica las rutinas de reparación sobre el proyecto VBA, corrigiendo referencias y módulos dañados.&quot; /&gt;
          &lt;/group&gt;
          &lt;group id=&quot;grpLogsSalir&quot; label=&quot;Ver Log y Salir&quot;&gt;
            &lt;button id=&quot;btnAbrirLogs&quot; 
                    label=&quot;Abrir carpeta de logs&quot; 
                    imageMso=&quot;FolderOpen&quot; 
                    onAction=&quot;Ribbon_AbrirCarpetaLogs&quot;
                    screentip=&quot;Abrir carpeta de logs&quot; 
                    supertip=&quot;Abre la carpeta donde el Inspector guarda los archivos de log diarios y de reparaciones.&quot; /&gt;
            &lt;button id=&quot;btnCerrar&quot; 
                    label=&quot;Cerrar&quot; 
                    imageMso=&quot;FileClose&quot; 
                    onAction=&quot;Ribbon_Cerrar&quot;
                    screentip=&quot;Cerrar Inspector&quot;
                    supertip=&quot;Cierra el formulario principal del Inspector VBA.&quot; /&gt;
          &lt;/group&gt;
        &lt;/tab&gt;
      &lt;/tabSet&gt;

      &lt;!-- ===================================================== --&gt;
      &lt;!-- CINTA PARA SUBFORMULARIO DE EXPORTACIONES --&gt;
      &lt;!-- ===================================================== --&gt;
      &lt;tabSet idMso=&quot;TabSetSubform&quot;&gt;
        &lt;tab id=&quot;tabInspectorExportar&quot; label=&quot;Inspector – Exportar&quot;&gt;
          &lt;group id=&quot;grpExportar&quot; label=&quot;Exportación&quot;&gt;
            &lt;dropDown id=&quot;cboFormato&quot; 
                      label=&quot;Formato&quot; 
                      onChange=&quot;Ribbon_CambioFormato&quot;
                      screentip=&quot;Seleccionar formato&quot;
                      supertip=&quot;Elige el formato de exportación (texto, Excel, HTML, etc.) para los resultados del Inspector.&quot; /&gt;
            &lt;dropDown id=&quot;cboEstilo&quot; 
                      label=&quot;Estilo HTML&quot; 
                      getVisible=&quot;Ribbon_MostrarEstilo&quot; 
                      onChange=&quot;Ribbon_CambioEstilo&quot;
                      screentip=&quot;Seleccionar estilo HTML&quot;
                      supertip=&quot;Elige el estilo visual para la exportación en formato HTML.&quot; /&gt;
            &lt;button id=&quot;btnExaminar&quot; 
                    label=&quot;Examinar...&quot; 
                    imageMso=&quot;FileSaveAs&quot; 
                    onAction=&quot;Ribbon_Examinar&quot;
                    screentip=&quot;Examinar ruta&quot;
                    supertip=&quot;Permite seleccionar la carpeta o archivo de destino para la exportación.&quot; /&gt;
            &lt;button id=&quot;btnExportar&quot; 
                    label=&quot;Exportar&quot; 
                    imageMso=&quot;ExportTextFile&quot; 
                    onAction=&quot;Ribbon_Exportar&quot;
                    screentip=&quot;Exportar resultados&quot;
                    supertip=&quot;Genera la exportación de los resultados del Inspector en el formato y estilo seleccionados.&quot; /&gt;
          &lt;/group&gt;
        &lt;/tab&gt;
      &lt;/tabSet&gt;

    &lt;/contextualTabs&gt;
  &lt;/ribbon&gt;

&lt;/customUI&gt;</RibbonXML>
</USysRibbons>
<USysRibbons>
<ID>4</ID>
<RibbonName>InspectorVBA</RibbonName>
<RibbonXML>&lt;customUI xmlns=&quot;http://schemas.microsoft.com/office/2009/07/customui&quot;&gt;
  &lt;ribbon&gt;
    &lt;tabs&gt;
      &lt;tab id=&quot;tabInspectorVBA&quot;
           label=&quot;Inspector VBA&quot;
           getVisible=&quot;Ribbon_InspectorVBA_Visible&quot;&gt;

        &lt;group id=&quot;grpLanzador&quot; label=&quot;Inspector&quot;&gt;
          &lt;button id=&quot;btnAbrirInspector&quot;
                  label=&quot;Abrir Inspector&quot;
                  imageMso=&quot;DatabaseFileOpen&quot;
                  onAction=&quot;Ribbon_AbrirInspector&quot;
                  screentip=&quot;Abrir Inspector&quot;
                  supertip=&quot;Abre el formulario del Inspector VBA.&quot; /&gt;
        &lt;/group&gt;

      &lt;/tab&gt;
    &lt;/tabs&gt;
  &lt;/ribbon&gt;
&lt;/customUI&gt;</RibbonXML>
</USysRibbons>
<USysRibbons>
<ID>5</ID>
<RibbonName>contextualTabSet</RibbonName>
<RibbonXML>&lt;customUI xmlns=&quot;http://schemas.microsoft.com/office/2009/07/customui&quot;&gt;

  &lt;ribbon&gt;
    &lt;contextualTabs&gt;

      &lt;!-- ===================================================== --&gt;
      &lt;!-- CINTA PARA FORMULARIO DE RESULTADOS --&gt;
      &lt;!-- ===================================================== --&gt;
      &lt;tabSet idMso=&quot;TabSetForm&quot;&gt;
        &lt;tab id=&quot;tabInspectorResultados&quot; label=&quot;Inspector – Resultados&quot;&gt;
          &lt;group id=&quot;grpAcciones&quot; label=&quot;Acciones&quot;&gt;
            &lt;button id=&quot;btnAnalizar&quot; 
                    label=&quot;Analizar&quot; 
                    imageMso=&quot;Zoom&quot; 
                    onAction=&quot;Ribbon_Analizar&quot; /&gt;
            &lt;button id=&quot;btnReparar&quot; 
                    label=&quot;Reparar&quot; 
                    imageMso=&quot;Repair&quot; 
                    onAction=&quot;Ribbon_Reparar&quot; /&gt;
          &lt;/group&gt;

          &lt;group id=&quot;grpLogsSalir&quot; label=&quot;Ver Log y Salir&quot;&gt;
            &lt;button id=&quot;btnAbrirLogs&quot; 
                    label=&quot;Abrir carpeta de logs&quot; 
                    imageMso=&quot;FolderOpen&quot; 
                    onAction=&quot;Ribbon_AbrirCarpetaLogs&quot; /&gt;
            &lt;button id=&quot;btnCerrar&quot; 
                    label=&quot;Cerrar&quot; 
                    imageMso=&quot;FileClose&quot; 
                    onAction=&quot;Ribbon_Cerrar&quot; /&gt;
          &lt;/group&gt;
        &lt;/tab&gt;
      &lt;/tabSet&gt;

      &lt;!-- ===================================================== --&gt;
      &lt;!-- CINTA PARA SUBFORMULARIO DE EXPORTACIONES --&gt;
      &lt;!-- ===================================================== --&gt;
      &lt;tabSet idMso=&quot;TabSetSubform&quot;&gt;
        &lt;tab id=&quot;tabInspectorExportar&quot; label=&quot;Inspector – Exportar&quot;&gt;
          &lt;group id=&quot;grpExportar&quot; label=&quot;Exportación&quot;&gt;

            &lt;dropDown id=&quot;cboFormato&quot;
